### ISSUE TITLE
potential MITM attack

### ISSUE THREAD

**Issue by s1155030508** [ierg4210/shop55#1]
visit /admin/login using http, there is no https digital certificate when i access /admin/login, i expect to see there is a https before your website url. add this to fix it:
app.use('/admin', function(req, res, next) {
var schema = req.headers['x-forwarded-proto'];
if (schema === 'https') {
//Already https; don't do anything special.
next();
}
else {
//// Redirect to https.
res.redirect('https://' + req.headers.host + req.url + '/admin');
}
});
![1](https://cloud.githubusercontent.com/assets/10615129/7548867/9d8045fc-f64f-11e4-8c60-820a7cd18f8b.png)

**Comment by wangjlgz** [comment]
I finished my demo yesterday and TA had already checked that part... I think you may have misunderstood the requirement. We just need to serve /admin on https. We do need to serve /admin/login on https.
![default](https://cloud.githubusercontent.com/assets/8156110/7548951/68c0b446-f654-11e4-9e3b-4735cc7eee5f.JPG)
